using System;
using System.Globalization;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using PROG6212_POE.Models;

namespace PROG6212_POE.Utilities
{
  
    public static class PdfGenerator
    {
        static PdfGenerator()
        {
            QuestPDF.Settings.License = LicenseType.Community;
        }
        public static byte[] GenerateInvoicePdf(InvoiceViewModel model)
        {
           
            var doc = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(30);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(11));

                    page.Header().Text($"Invoice for {model.Lecturer.Name} {model.Lecturer.Surname}")
                        .SemiBold().FontSize(16);

                    page.Content().PaddingVertical(10).Column(column =>
                    {
                        column.Item().Row(row =>
                        {
                            row.RelativeItem().Column(c =>
                            {
                                c.Item().Text($"Lecturer ID: {model.Lecturer.LecturerID}");
                                c.Item().Text($"Name: {model.Lecturer.Name} {model.Lecturer.Surname}");
                                c.Item().Text($"Email: {model.Lecturer.Email}");
                            });
                            row.ConstantItem(200).AlignRight().Column(c =>
                            {
                                c.Item().Text($"Date: {DateTime.Now:yyyy-MM-dd}");
                                c.Item().Text($"Invoice #: {Guid.NewGuid().ToString().Substring(0, 8).ToUpper()}");
                            });
                        });

                        column.Item().PaddingTop(10).Element(ComposeClaimTable(model));

                        column.Item().PaddingTop(10).AlignRight()
                            .Text($"Total: {model.TotalAmount.ToString("C", CultureInfo.CurrentCulture)}")
                            .SemiBold();
                    });

                    page.Footer().AlignCenter().Text("Generated by Monthly Claim System");
                });
            });

            return doc.GeneratePdf();
        }

        private static Action<IContainer> ComposeClaimTable(InvoiceViewModel model)
        {
            return container =>
            {
                container.Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.ConstantColumn(60);  // ClaimID
                        columns.RelativeColumn();    // Sessions
                        columns.ConstantColumn(70);  // Hours
                        columns.ConstantColumn(80);  // Rate
                        columns.ConstantColumn(90);  // Amount
                    });

                    table.Header(header =>
                    {
                        header.Cell().Element(CellStyle).Text("Claim ID").Bold();
                        header.Cell().Element(CellStyle).Text("Sessions").Bold();
                        header.Cell().Element(CellStyle).Text("Hours").Bold();
                        header.Cell().Element(CellStyle).Text("Hourly Rate").Bold();
                        header.Cell().Element(CellStyle).Text("Amount").Bold();
                    });

                    foreach (var c in model.ApprovedClaims)
                    {
                        table.Cell().Element(CellStyle).Text(c.ClaimID.ToString());
                        table.Cell().Element(CellStyle).Text($"{c.Sessions} session(s)");
                        table.Cell().Element(CellStyle).Text(c.HoursWorked.ToString());
                        table.Cell().Element(CellStyle).Text(c.HourlyRate.ToString("C", CultureInfo.CurrentCulture));
                        table.Cell().Element(CellStyle).Text(c.Amount.ToString("C", CultureInfo.CurrentCulture));
                    }

                    static IContainer CellStyle(IContainer container)
                    {
                        return container.PaddingVertical(5).PaddingHorizontal(5).Border(1).BorderColor(Colors.Grey.Lighten2);
                    }
                });
            };
        }
    }
}